/* #undef SDL2COMPAT_VENDOR_INFO */
#define SDL_REVISION_NUMBER 0

#ifdef SDL2COMPAT_VENDOR_INFO
#define SDL_REVISION "SDL-2.32.57-g1577bce (" SDL2COMPAT_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.32.57-g1577bce"
#endif
